<center><font  color=#FFFFFF>
<font color="888888">|</font>
<font color="#CCCCCC">文</font>
<font color="888888">|</font>
<font color="#CCCCCC">藻</font>
<font color="888888">|</font>
<font color="#CCCCCC">外</font>
<font color="888888">|</font>
<font color="#CCCCCC">語</font>
<font color="888888">|</font>
<font color="#CCCCCC">學</font>
<font color="888888">|</font>
<font color="#CCCCCC">院</font>
<font color="888888">|</font>
預約相關問題請洽LDCC分機7403 或 ELC分機5311
　
系統維護請洽資教中心 -- 林怡辰 分機2856</font>
</center>

