<TABLE cellSpacing=0 cellPadding=0 border=0 >
<TR>
<TD><a href="#" title="英外語診斷輔導中心　預約規則" onclick="window.open('showrule.asp','','fullscreen=1,scrollbars=1');" ><img src="images/icon_question.gif" border="0"></a>&nbsp;&nbsp;</TD>
<TD><img src="images/2-1.gif" border="0">&nbsp;</TD>
<TD><font  color=#FFCC00><%=session("dept")%></font>&nbsp;<font  color=#669900>|</font>&nbsp;</TD>
<TD><font  color=#FFCC00><%=session("sname")%>(&nbsp;<%=replace(replace(replace(session("classify"),"S","學員"),"A","管理者"),"T","老師")%>&nbsp;)</font>&nbsp;&nbsp;&nbsp;</TD>
</TR>
</TABLE>
